### ISSUE TITLE
When I ran truffle compile, errors occured. 

### ISSUE THREAD

**Issue by dannyng1988** [SunPaz/EtherTrack#13]
Dannys-Air:EtherTrack dannyng$ sudo truffle compile

Compiling your contracts...
===========================
✖ Fetching solc version list from solc-bin. Attempt #1
✖ Fetching solc version list from solc-bin. Attempt #2
✖ Fetching solc version list from solc-bin. Attempt #3
Error: Could not find a compiler version matching 0.5.16. Please ensure you are specifying a valid version, constraint or build in the truffle config. Run `truffle compile --list` to see available versions.
    at VersionRange.errors (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/loadingStrategies/LoadingStrategy.js:66:1)
    at VersionRange.getSatisfyingVersionFromCache (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/loadingStrategies/VersionRange.js:81:1)
    at VersionRange.load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/loadingStrategies/VersionRange.js:197:1)
Truffle v5.1.46 (core: 5.1.46)
Node v12.13.0

**Comment by ddb1** [comment]
？？？

**Comment by MatthAmoros** [comment]
Guys I m really sorry but this project has been discontinued a few years agos. Solidity version is way out-dated.
I will update the ReadMe to clarify this situation.
